name: Clean Docs
description: Cleans documentation files using clean_markdown.py
inputs:
  config_path:
    description: 'Path to the configuration file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pyyaml
      shell: bash

    - name: Run cleaner
      run:  python ${{ github.action_path }}/scripts/clean_markdown.py ${{ inputs.config_path }}
      shell: bash
